### ISSUE TITLE
Missing & deprecated dependencies on fresh install

### ISSUE THREAD

**Issue by SumitBando** [nhristov/sapper-template-firebase#1]
npm WARN deprecated rollup-plugin-babel@4.4.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-babel.

> protobufjs@6.9.0 postinstall /private/tmp/sapper-template-firebase/node_modules/protobufjs
> node scripts/postinstall

> svelte-preprocess@3.7.4 postinstall /private/tmp/sapper-template-firebase/node_modules/svelte-preprocess
> echo "[svelte-preprocess] Don't forget to install the preprocessors packages that will be used: node-sass/sass, stylus, less, postcss & postcss-load-config, coffeescript, pug, etc..."

[svelte-preprocess] Don't forget to install the preprocessors packages that will be used: node-sass/sass, stylus, less, postcss & postcss-load-config, coffeescript, pug, etc...
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN @rollup/plugin-commonjs@11.0.2 requires a peer of rollup@^1.20.0 but none is installed. You must install peer dependencies yourself.
npm WARN svelte-preprocess@3.7.4 requires a peer of coffeescript@^2.5.1 but none is installed. You must install peer dependencies yourself.
npm WARN svelte-preprocess@3.7.4 requires a peer of less@^3.10.3 but none is installed. You must install peer dependencies yourself.
npm WARN svelte-preprocess@3.7.4 requires a peer of node-sass@^4.13.1 but none is installed. You must install peer dependencies yourself.
npm WARN svelte-preprocess@3.7.4 requires a peer of pug@^2.0.4 but none is installed. You must install peer dependencies yourself.
npm WARN svelte-preprocess@3.7.4 requires a peer of sass@^1.26.3 but none is installed. You must install peer dependencies yourself.
npm WARN svelte-preprocess@3.7.4 requires a peer of stylus@^0.54.7 but none is installed. You must install peer dependencies yourself.
npm WARN svelte-preprocess@3.7.4 requires a peer of typescript@^3.7.5 but none is installed. You must install peer dependencies yourself.

**Comment by nhristov** [comment]
Hi, thx I'll clean them up today.
