### ISSUE TITLE
NPM install dependency issue

### ISSUE THREAD

**Issue by myangga** [nhristov/sapper-template-firebase#7]
Hi,

Just tried to degit your repo, and got this issue on npm install:

`npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: postcss-load-config@3.0.0
npm ERR! node_modules/postcss-load-config
npm ERR!   dev postcss-load-config@"3.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional postcss-load-config@"^2.1.0" from svelte-preprocess@4.6.1
npm ERR! node_modules/svelte-preprocess
npm ERR!   dev svelte-preprocess@"4.6.1" from the root project`

**Comment by nhristov** [comment]
Hello, I just tried

```bash
npx degit "nhristov/sapper-template-firebase#main" my-app
```

then

```bash
npm install && npm run build
```

but didn't run into any issues. Can you maybe share your Node / NPM version? I'm running this on **node v14.15.4** and **npm 6.14.10**

**Comment by myangga** [comment]
my bad. Now worked. As I use NVM, i may have used different version of node/npm before - 15.x. 
<img width="881" alt="Screenshot 2021-01-21 124014" src="https://user-images.githubusercontent.com/1888914/105346626-27024d00-5be6-11eb-9b1c-f631ab7eb459.png">

Many thanks for your prompt feedback and check.
